In [1]:
import torch
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
a = np.expand_dims(a, axis=0)
print(a.shape)

(1, 5)


In [6]:
at = torch.Tensor(a)
at

tensor([[1., 2., 3., 4., 5.]])

In [7]:
at.view(-1) ## view로 다른 size 값을 명시하지 않고 -1만 실행했을 경우 squeeze와 같은 결과를 보임.

tensor([1., 2., 3., 4., 5.])