In [1]:
import torch
import numpy as np

from torch import nn
from torch import optim

In [2]:
sample_data = "hihello"

In [3]:
char_set = list(set(sample_data))
char_set.sort()
print(char_set)

sample_label = [char_set.index(c) for c in sample_data]
print(f"{sample_data} ==> {sample_label}")

['e', 'h', 'i', 'l', 'o']
hihello ==> [1, 2, 1, 0, 3, 3, 4]


In [4]:
np.eye(len(char_set))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
x = [sample_label[:-1]]
print(x)

x_one_hot = [np.eye(len(char_set))[x] for x in x]
print(x_one_hot)

y = [sample_label[1:]]
print(y)

[[1, 2, 1, 0, 3, 3]]
[array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])]
[[2, 1, 0, 3, 3, 4]]


In [10]:
X = torch.tensor(np.array(x_one_hot), dtype=torch.float32)
Y = torch.tensor(y, dtype=torch.int64)
h0 = torch.zeros(1, 1, len(char_set))

print(X.shape, Y.shape)
print(X)
print(Y)

torch.Size([1, 6, 5]) torch.Size([1, 6])
tensor([[[0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]])
tensor([[2, 1, 0, 3, 3, 4]])


In [7]:
input_dim = len(char_set)
hidden_dim = len(char_set)

print(input_dim, hidden_dim)

5 5


In [8]:
learning_rate = 0.01

model = nn.RNN(input_dim, hidden_dim, batch_first=True)
criterion = nn.CrossEntropyLoss() ## Multi-class classification
optimizer = optim.Adam(model.parameters(), learning_rate)

In [9]:
for i in range(100):
    optimizer.zero_grad()

    outputs, status = model(X)
    
    loss = criterion(outputs.view(-1, input_dim), Y.view(-1))
    loss.backward()
    optimizer.step()

    result = outputs.data.numpy().argmax(axis=2)
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])

    print(f"epoch{i} | loss : {loss.item()}, prediction : {result_str}")

torch.Size([1, 6, 5]) torch.Size([1, 1, 5])
torch.Size([6, 5]) torch.Size([6])


epoch0 | loss : 1.6777125597000122, prediction : eeehoo
epoch1 | loss : 1.643537998199463, prediction : eeehoo
epoch2 | loss : 1.6106500625610352, prediction : eeehoo
epoch3 | loss : 1.5792425870895386, prediction : eeehoo
epoch4 | loss : 1.5494645833969116, prediction : eelhoo
epoch5 | loss : 1.5214167833328247, prediction : eelhoo
epoch6 | loss : 1.4951480627059937, prediction : eelhoo
epoch7 | loss : 1.4706486463546753, prediction : eelhoo
epoch8 | loss : 1.4478541612625122, prediction : eelhoo
epoch9 | loss : 1.4266513586044312, prediction : eelhoo
epoch10 | loss : 1.4068894386291504, prediction : ehlhoo
epoch11 | loss : 1.3883975744247437, prediction : ehlllo
epoch12 | loss : 1.3710013628005981, prediction : ehlllo
epoch13 | loss : 1.354535460472107, prediction : ehlllo
epoch14 | loss : 1.338849663734436, prediction : ehlllo
epoch15 | loss : 1.3238134384155273, prediction : ehlllo
epoch16 | loss : 1.3093138933181763, prediction : ehlllo
epoch17 | loss : 1.2952560186386108, predict