In [1]:
import torch

In [2]:
width, height = 13, 13

In [6]:
lin_x = torch.arange(0, width).repeat(height, 1).view(height * width)
lin_y = torch.arange(0, height).repeat(width, 1).t().contiguous().view(height * width)

print(lin_x)
print(lin_y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,
         2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,
         1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12])
tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
   

In [ ]:
anchors = [(1.3221, 1.73145), 
           (3.19275, 4.00944), 
           (5.05587, 8.09892), 
           (9.47112, 4.84053), 
           (11.2364, 10.0071)]

num_anchors = len(anchors)
anchors = torch.tensor(anchors)

In [3]:
anchor_w = anchors[:, 0].contiguous().view(num_anchors, 1)
anchor_h = anchors[:, 1].contiguous().view(num_anchors, 1)

In [4]:
print(anchor_w)
print(anchor_h)

tensor([[ 1.3221],
        [ 3.1927],
        [ 5.0559],
        [ 9.4711],
        [11.2364]])
tensor([[ 1.7314],
        [ 4.0094],
        [ 8.0989],
        [ 4.8405],
        [10.0071]])
