In [1]:
import torch
from torch import nn

In [2]:
X = torch.tensor([[0.5, 0.6, 0.7],
                  [1.5, 1.6, 1.7],
                  [2.5, 2.6, 2.7]]) ## [3,]인 데이터 샘플의 mini-batch. batch_size=3

Y = torch.tensor([[2.0],
                  [3.5],
                  [5.0]]) ## labels

print(f"Mini-batch X : {X.shape}, \n {X} \n")
print(f"Mini-batch Y : {Y.shape}, \n {Y} \n")

Mini-batch X : torch.Size([3, 3]), 
 tensor([[0.5000, 0.6000, 0.7000],
        [1.5000, 1.6000, 1.7000],
        [2.5000, 2.6000, 2.7000]]) 

Mini-batch Y : torch.Size([3, 1]), 
 tensor([[2.0000],
        [3.5000],
        [5.0000]]) 



In [3]:
layer = nn.Linear(Y.size(0), Y.size(1))

W = layer.weight
b = layer.bias
print(f"Weight matrix : {W.shape}, \n {W} \n")
print(f"bias vector : {b.shape}, \n {b} \n")

Weight matrix : torch.Size([1, 3]), 
 Parameter containing:
tensor([[0.4246, 0.3559, 0.0997]], requires_grad=True) 

bias vector : torch.Size([1]), 
 Parameter containing:
tensor([-0.2811], requires_grad=True) 



In [6]:
Y_hat = layer(X)
print(Y_hat.shape)
print(Y_hat)

torch.Size([3, 1])
tensor([[0.2145],
        [1.0947],
        [1.9749]], grad_fn=<AddmmBackward0>)


In [7]:
loss_func = nn.MSELoss()
L = loss_func(Y_hat, Y)
print(L)

tensor(6.0416, grad_fn=<MseLossBackward0>)
